### PR TITLE
MAT-4877 use component for error, warning, success messages for Test …

### PR DESCRIPTION
**Pull request by sb-cecilialiu**
…Case List page

## MADiE PR

Jira Ticket: [MAT-4877](https://jira.cms.gov/browse/MAT-4877)
(Optional) Related Tickets:

### All Submissions
* [x] This PR has the JIRA linked.
* [ ] Required tests are included
* [x] No extemporaneous files are included (i.e Complied files or testing results)
* [x] This PR is into the **correct branch**.
* [ ] All Documentation as needed for this PR is Complete (or noted in a TODO or other Ticket)
* [ ] Any breaking changes or failing automation are noted by placing a comment on this PR.

### DevSecOps
If there is a question if this PR has a security or infrastructure impact, please contact the Security or DevOps engineer assigned to this project to discuss it further.

* [x] This PR has NO significant security impact (i.e Changing auth methods, Adding a new user type, Adding a required but vulnerable package)
* [ ] All CDN/Web dependencies are hosted internally (i.e MADiE-Root Repo)

### Reviewers
By Approving this PR you are attesting to the following:

*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

### CODE REVIEW

**Comment by sb-cecilialiu** [comment]
Pasted Graphic

**Comment by sb-cecilialiu** [comment]
Pasted Graphic

**Comment by sb-cecilialiu** [comment]
Pasted Graphic 1

**Comment by mcmcphillips** [comment]
https://www.figma.com/file/1RPYLI39hfMczAL81ARArX/MADiE-Application?node-id=7153%3A68992&t=1Wxli9Cpa2KIn941-4

image


I think this is how it's expected to look. There's a MadieAlert component that can be used for this from design system

**Comment by sb-cecilialiu** [comment]
@mcmcphillips I'm using the same component to replace the different Alerts, so it's consistent with other apps. For Test Case List page, there is no listed errors like what Measure updates would have with CQL errors.

**Review by adongare — DISMISSED** [review]

**Comment by mcmcphillips** [comment]
> @mcmcphillips I'm using the same component to replace the different Alerts, so it's consistent with other apps. For Test Case List page, there is no listed errors like what Measure updates would have with CQL errors.

The alert component does not only take lists. 
It takes a prop called content that can be html strings. 
The alert component also does not appear to be in the same place. You can make a single alert component the highest level of the component heirarchy, and pass props to the other components that allow them to update the state. You can blank the alert state whenever you'd want

**Comment by sb-cecilialiu** [comment]
image

**Review by mcmcphillips — APPROVED** [review]
This looks good to me

**Pull request merged**
